### PR TITLE
Get rid of ctypes dependency to make persistent more pure-python compatible

### PR DESCRIPTION
**Pull request by michwill**
In order to work with max integers, persistent uses ctypes. It is not really necessary but breaks compatibility with pypy.js, for example.

### CODE REVIEW

**Comment by tseaver** [comment]
Breaks Py3k, which has no `sys.maxint`.

**Comment by michwill** [comment]
Indeed. Is it correct to use sys.maxsize for Py3k?

**Comment by tseaver** [comment]
@michwill `sys.maxsize` should work on all the platforms we care about.

**Comment by tseaver** [comment]
Rather than  monkey-patching `sys`, please initialize a constant (e.g., `_MAXSIZE`) in the `timestamp` module, and then monkey-patch *that* value in the tests.

**Comment by tseaver** [comment]
I will tackle fixing up the branch to use `sys.maxsize` and do the monkey-patch I suggested.

**Comment by tseaver** [comment]
@michwill Thank you for the patch!

**Pull request merged**
