### PR TITLE
Config with c code + Add support for Python 3.10.

### PR DESCRIPTION
**Pull request by icemac**
Open issues:

- [ ] Sphinx doctests break locally for pure-python versions (see below) – I do not know why

### CODE REVIEW

**Comment by icemac** [comment]
Local failure when running tests using pure-python:

```python
$ tox -epy38-pure
py38-pure develop-inst-noop: /.../persistent
py38-pure installed: alabaster==0.7.12,Babel==2.9.1,certifi==2021.10.8,cffi==1.15.0,charset-normalizer==2.0.11,docutils==0.17.1,idna==3.3,imagesize==1.3.0,importlib-metadata==4.10.1,Jinja2==3.0.3,manuel==1.10.1,MarkupSafe==2.0.1,packaging==21.3,-e git+https://github.com/zopefoundation/persistent@22dd80df0895248a6529be357592429b1d1356e3#egg=persistent,pycparser==2.21,Pygments==2.11.2,pyparsing==3.0.7,pytz==2021.3,repoze.sphinx.autointerface==0.8,requests==2.27.1,six==1.16.0,snowballstemmer==2.2.0,Sphinx==4.4.0,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==2.0.0,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.5,urllib3==1.26.8,zipp==3.7.0,zope.exceptions==4.4,zope.interface==5.4.0,zope.testrunner==5.4.0
py38-pure run-test-pre: PYTHONHASHSEED='1652147971'
py38-pure run-test: commands[0] | zope-testrunner --test-path=src -vc
Running tests at level 1
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Running:
......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
  Ran 774 tests with 0 failures, 0 errors, 245 skipped in 0.686 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
py38-pure run-test: commands[1] | sphinx-build -b doctest -d /.../persistent/.tox/py38-pure/.cache/doctrees docs /.../persistent/.tox/py38-pure/.cache/doctest
Sphinx v4.4.0 in Verwendung
WARNING: html_static_path entry '_static' does not exist
loading pickled environment... erledigt
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
building [doctest]: targets for 10 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
running tests...

Document: using
---------------
**********************************************************************
File "using.rst", line 246, in default
Failed example:
    p._p_deactivate()
Exception raised:
    Traceback (most recent call last):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[0]>", line 1, in <module>
        p._p_deactivate()
      File "/.../persistent/src/persistent/persistence.py", line 433, in _p_deactivate
        self._p_invalidate_deactivate_helper()
      File "/.../persistent/src/persistent/persistence.py", line 480, in _p_invalidate_deactivate_helper
        cache.update_object_size_estimation(_OGA(self, '_Persistent__oid'), -1)
    AttributeError: 'Cache' object has no attribute 'update_object_size_estimation'
**********************************************************************
File "using.rst", line 289, in default
Failed example:
    p._p_invalidate()
Exception raised:
    Traceback (most recent call last):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[0]>", line 1, in <module>
        p._p_invalidate()
      File "/.../persistent/src/persistent/persistence.py", line 441, in _p_invalidate
        self._p_deactivate()
      File "/.../persistent/src/persistent/persistence.py", line 433, in _p_deactivate
        self._p_invalidate_deactivate_helper()
      File "/.../persistent/src/persistent/persistence.py", line 480, in _p_invalidate_deactivate_helper
        cache.update_object_size_estimation(_OGA(self, '_Persistent__oid'), -1)
    AttributeError: 'Cache' object has no attribute 'update_object_size_estimation'
**********************************************************************
File "using.rst", line 317, in default
Failed example:
    p._p_invalidate()
Exception raised:
    Traceback (most recent call last):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[0]>", line 1, in <module>
        p._p_invalidate()
      File "/.../persistent/src/persistent/persistence.py", line 441, in _p_invalidate
        self._p_deactivate()
      File "/.../persistent/src/persistent/persistence.py", line 433, in _p_deactivate
        self._p_invalidate_deactivate_helper()
      File "/.../persistent/src/persistent/persistence.py", line 480, in _p_invalidate_deactivate_helper
        cache.update_object_size_estimation(_OGA(self, '_Persistent__oid'), -1)
    AttributeError: 'Cache' object has no attribute 'update_object_size_estimation'
**********************************************************************
1 items had failures:
   3 of  98 in default
98 tests in 1 items.
95 passed and 3 failed.
***Test Failed*** 3 failures.

Document: api/cache
-------------------
1 items passed all tests:
  11 tests in default
11 tests in 1 items.
11 passed and 0 failed.
Test passed.

Document: api/pickling
----------------------
1 items passed all tests:
  68 tests in default
68 tests in 1 items.
68 passed and 0 failed.
Test passed.

Document: api/attributes
------------------------
1 items passed all tests:
  80 tests in default
80 tests in 1 items.
80 passed and 0 failed.
Test passed.

Doctest summary
===============
  257 tests
    3 failures in tests
    0 failures in setup code
    0 failures in cleanup code
build mit Problemen beendet, 1 warning.
ERROR: InvocationError for command /.../persistent/.tox/py38-pure/bin/sphinx-build -b doctest -d .tox/py38-pure/.cache/doctrees docs .tox/py38-pure/.cache/doctest (exited with code 1)

====================================================================== log end =======================================================================
✖ FAIL py38-pure in 7.529 seconds
```

What could cause this problem?

**Comment by icemac** [comment]
@jamadden Do you have any idea about the locally broken tests?

**Comment by d-maurer** [comment]
> What could cause this problem?

`persistence.Persistent` (at least the Python implementation) expects a data manager which either has no cache or a `PickleCache`. But the doctest sets up data manager with a trivial cache (which lacks `PickleCache`'s `update_object_size_estimation`).

I suggest you remove the cache association from the data manager and check whether this lets all tests succeed (apparently, the doctest itself does not need the cache).

Note also the typo in `using.rst` at line 227: `persistent.Persistent._p_activate_p_deactivate` should be `persistent.Persistent._p_deactivate`.

**Review by d-maurer — APPROVED** [review]
From my point of view, it looks good -- but, I do not have experience with most of the files changed by this PR.

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Comment by icemac** [comment]
I'll try it and create a release.

**Pull request merged**
